registered/urls.py
from django.urls import path
from registered import views


app_name = "registered"


urlpatterns = [
    path("", views.register, name="register"),
    path('delete/<int:id>/',views.delete, name="delete"),
    path('edit/<int:id>/',views.edit, name="edit")
]

registrationForm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path("user/", include("users.urls", namespace="users")),
    path("register/", include("registered.urls", namespace="registered"))
]

web/urls.py
from django.urls import path

from web import views


app_name = "web"


urlpatterns = [
    path("", views.index, name="index"),
    path("logged-in/", views.register, name="userPage"),
    path("participant-details/<int:id>/", views.details, name="details")
]

templates/web/index.html
{% extends "base.html" %} {% load static %} {% block content %}
<section id="home">
  {% include 'web/includes/header.html' %}
  <section class="spotLight center">
    <section class="wrapper">
      <section class="spotlight">
        <h2>
          <span>Arts Fest</span> <br />
          Registration
        </h2>
        <p>Haven't you registered yet?</p>
        <a href="{% url 'registered:register' %}" class="register"
          >Register Here</a
        >
      </section>
    </section>
  </section>
</section>
{% endblock %}

templates/web/register.html
{% extends "user_base.html" %} {% block content %} {% load static %}
<section class="form_container register">
  <div class="top">
    <h4>ARTS FEST</h4>
    <h5>Register your Application</h5>
  </div>
  <div class="bottom">
    <form class="ajax redirect" action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="input_container">
        <label for="{{form.first_name.id_for_label}}">
          {{form.first_name.label}}
        </label>
        {{form.first_name}}
        <!-- <input type="text" name="first_name" /> -->
      </div>
      <div class="input_container">
        <label for="{{form.last_name.id_for_label}}">
          {{form.last_name.label}}
        </label>
        {{form.last_name}}
        <!-- <input type="text" name="last_name" /> -->
      </div>
      <div class="input_container">
        <label for="{{form.date_of_birth.id_for_label}}">
          {{form.date_of_birth.label}}
        </label>
        {{form.date_of_birth}}

        <!-- <input type="text" name="date_of_birth" /> -->
      </div>
      <div class="input_container">
        <label for="{{form.gender.id_for_label}}">
          {{form.gender.label}}
        </label>
        {{form.gender}}
      </div>
      <div class="input_container">
        <label for="{{form.email.id_for_label}}"> Email </label>
        {{form.email}}
        <!-- <input type="email" name="email" /> -->
      </div>
      <div class="input_container">
        <label for="{{form.contact_number.id_for_label}}"> Mobile No. </label>
        {{form.contact_number}}
        <!-- <input type="text" name="contact_number" /> -->
      </div>
      <div class="input_container">
        <label for="{{form.school_grade.id_for_label}}"> Class </label>
        {{form.school_grade}}
      </div>
      <div class="input_container">
        <label for="{{form.item.id_for_label}}"> Participating Item </label>
        {{form.item}}
      </div>
      <div class="submit_container"><button type="submit">Submit</button></div>
    </form>
  </div>
</section>
{% endblock %}