registrationForm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path("user/", include("users.urls", namespace="users")),
    path("register/", include("registered.urls", namespace="registered"))
]

web/urls.py
from django.urls import path

from web import views


app_name = "web"


urlpatterns = [
    path("", views.index, name="index"),
    path("logged-in/", views.register, name="userPage"),
    path("participant-details/<int:id>/", views.details, name="details")
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <title>Registration Form</title>
    <link
      rel="stylesheet"
      href="{% static './css/style.css' %}"
      type="text/css"
    />
    <!-- <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static './images/icons/blog-logo.svg' %}"
    /> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:image" content="" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <script src="{% static './js/jquery-3.6.0.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static './js/script.js' %}"></script>
    <!-- <script src="{% static './js/ckeditor.js' %}"></script> -->
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

templates/user_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/user-style.css' %}" />
    <script src="{% static './js/jquery-3.6.0.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static './js/script.js' %}"></script>

    <title>Login</title>
  </head>
  <body>
    <section class="container">
      <header>
        <h1>
          <a href="{% url 'web:index' %}">
            <h3><b>XYZ School</b></h3>
          </a>
        </h1>
      </header>
      <section id="form">{% block content %} {% endblock %}</section>
    </section>
  </body>
</html>