registered/urls.py
from django.urls import path
from registered import views


app_name = "registered"


urlpatterns = [
    path("", views.register, name="register"),
    path('delete/<int:id>/',views.delete, name="delete"),
    path('edit/<int:id>/',views.edit, name="edit")
]

registrationForm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path("user/", include("users.urls", namespace="users")),
    path("register/", include("registered.urls", namespace="registered"))
]

users/urls.py
from django.urls import path
from users import views


app_name = "users"


urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
]

web/urls.py
from django.urls import path

from web import views


app_name = "web"


urlpatterns = [
    path("", views.index, name="index"),
    path("logged-in/", views.register, name="userPage"),
    path("participant-details/<int:id>/", views.details, name="details")
]

users/models.py
from django.db import models


class SignedupUser(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField("auth.User",on_delete=models.CASCADE)

    def __str__(self):
        return self.name

users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "username", "password"]
        widgets = {
            "password" :  forms.widgets.PasswordInput(attrs={"placeholder":"Enter strong password"})
        }
    

users/views.py
from django.shortcuts import render,reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User

from main.functions import generate_form_errors
from users.forms import UserForm
from users.models import SignedupUser


#School official's LOGIN function 
def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request,user)

                return HttpResponseRedirect("/logged-in/")
 
        context={
            "error":True,
            "message": "Invalid username or password"
        }
        return render(request, "users/login.html",context=context)
    else:
        context = {}
        return render(request, "users/login.html", context=context)
 

#School official's LOGOUT function
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("web:index"))


#School official's SIGNUP function
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            user = User.objects.create_user(
                username=instance.username,
                password=instance.password,
                email=instance.email,
                first_name=instance.first_name,
                last_name=instance.last_name
            )
            user.save()

            SignedupUser.objects.create(name=instance.first_name, user=user)

            user = authenticate(request,username=instance.username, password=instance.password)
            auth_login(request,user)

            return HttpResponseRedirect(reverse("web:index"))
        else:
            message = generate_form_errors(form)
               
            form = UserForm()
            context = {
                "error": True,
                "message": message,
                "form": form,
            }
            return render(request, "users/signup.html", context=context)
    else:
        form = UserForm()
        context = {
            "form": form,
        }
        return render(request, "users/signup.html", context=context)
    

templates/users/login.html
{%extends "user_base.html" %} {% load static %} {% block content %}
<section class="form_container">
  <div class="top">
    <h5>School officials login with your credentials.<h5>
  </div>
  <div class="bottom">
    <form action="" method="post">
      {% csrf_token %}
      <div class="input_container">
        <label for="id_username"> Username </label>
        <input id="id_username" name="username" type="text" />
      </div>
      <div class="input_container">
        <label for="id_password"> Password </label>
        <input id="id_password" name="password" type="password" />
      </div>
      <div class="submit_container">
        {% if error %}
        <p class="error-message">{{message}}</p>
        {% endif %}
        <button type="submit">Login</button>

        <a href="{% url 'users:signup' %}">Create Account</a>
      </div>
    </form>
  </div>
</section>
{% endblock %}

templates/users/signup.html
{%extends "user_base.html" %} {% load static %} {% block content %}
<section class="form_container signup">
  <div class="top">
    <h5>Signup</h5>
  </div>
  <div class="bottom">
    <form action="" method="post">
      {% csrf_token %}
      <div class="signup">
        {% for field in form %}
        <div class="input_container signup">
          <label for="{{field.id_for_label}}"> {{field.label}} </label>
          {{field}}
        </div>
        {% endfor %}
      </div>
      <div class="submit_container">
        {% if error %}
        <p class="error-message">{{message}}</p>
        {% endif %}
        <button type="submit">Create Account</button>

        <a href="{% url 'users:login' %}">Login</a>
      </div>
    </form>
  </div>
</section>
{% endblock %}

templates/users/userPage.html
{% extends "base.html" %} {% load static %} {% block content %}
<section id="home">
  {% include 'web/includes/header.html' %}
  <section class="spotLight">
    <section class="wrapper logged_in">
      <section class="spotlight">
        <h3>List of Registered Students</h3>
        <div class="container">
          <table class="table">
            <thead>
              <tr class="thead">
                <th><span>Name</span></th>
                <th><span>Class</span></th>
                <th><span>Participating Item</span></th>
                <th>&nbsp;</th>
              </tr>
            </thead>
            <tbody>
              {% for participant in participants %}
              <tr class="tbody">
                <td>
                  <a
                    href="{% url 'web:details' id=participant.id %}"
                    class="name"
                    >{{participant.first_name}} {{participant.last_name}}</a
                  >
                </td>
                <td>
                  <span>{{participant.school_grade}}</span>
                </td>
                <td>
                  <span class="item">{{participant.item}}</span>
                </td>
                <td class="edit" style="width: 20%">
                  <a
                    href="{% url 'registered:edit' id=participant.id %}"
                    class="table-link reload"
                  >
                    <div class="img">
                      <img src="{% static 'images/pen.png' %}" />
                    </div>
                  </a>
                  <a
                    href="{% url 'registered:delete' id=participant.id %}"
                    class="action-button reload"
                  >
                    <div class="img">
                      <img src="{% static 'images/delete.png' %}" />
                    </div>
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </section>
    </section>
  </section>
</section>
{% endblock %}